language: go
go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get -d -t -v ./...
  - go build -x -v ./...
  - go test -a -x -v ./...
  - diff <(gofmt -d .) <("")
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .travis/test-coverage.sh; fi
